apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-root-username: dXNlcm5hbWU= # echo -n 'username' | base64 
    mysql-root-password: cjAwdA== # echo -n 'r00t' | base64
    mysql-user-password: Y0BsbDFjMGQzcg== # echo -n 'c@ll1c0d3r' | base64